name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '1.22'
      - run: go build -o osv2mov .
      - uses: actions/upload-artifact@v4
        with:
          name: osv2mov
          path: osv2mov
