name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '1.22'
          cache: true
      - name: Download dependencies
        run: go mod download
      - run: go build -o osv2mov .
      - uses: actions/upload-artifact@v4
        with:
          name: osv2mov
          path: osv2mov

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: osv2mov
          path: .
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: osv2mov
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
